#!/usr/bin/env python3
"""Generate docker-compose.yml for N Worldwalker RPG player instances.

Regenerate the file with this script instead of hand-copying service blocks
when the player count changes — keeps every player's block consistent
(resource limits, optional auth env vars, etc).

Usage:
    python generate-compose.py <player_count> [start_port]

Examples:
    python generate-compose.py 5        # players 1-5, ports 5001-5005
    python generate-compose.py 3 6000   # players 1-3, ports 6001-6003
"""
import sys

HEADER = """\
# One Worldwalker RPG game is one shared state per running instance — it is
# NOT multiplayer in the sense of several people sharing one character or
# world. Each player gets their own isolated container, port, and data
# volume below.
#
# Auto-generated by generate-compose.py — re-run that script to change the
# player count rather than hand-editing this file.
#
# Usage:
#   docker compose up -d --build
# Each player then connects to http://<nas-ip>:<their-port>/ in a browser.
#
# AUTH_USER / AUTH_PASS are optional — uncomment and set both to require a
# login for that player's instance. See LINUX_SERVER_README.txt.

services:
"""

SERVICE_TEMPLATE = """\
  worldwalker-player{i}:
    build: .
    container_name: worldwalker-player{i}
    mem_limit: 1g
    cpus: 1.0
    ports:
      - "{port}:8765"
    volumes:
      - ./data/player{i}:/data
    environment:
      # - AUTH_USER=player{i}
      # - AUTH_PASS=changeme{i}
    restart: unless-stopped
"""


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    count = int(sys.argv[1])
    start_port = int(sys.argv[2]) if len(sys.argv) > 2 else 5000

    parts = [HEADER]
    for i in range(1, count + 1):
        parts.append(SERVICE_TEMPLATE.format(i=i, port=start_port + i))
        parts.append("\n")

    with open("docker-compose.yml", "w", newline="\n") as f:
        f.write("".join(parts))

    print(
        f"Wrote docker-compose.yml with {count} player service(s), "
        f"ports {start_port + 1}-{start_port + count}."
    )


if __name__ == "__main__":
    main()
