"""Authored original situations, not canon facts or procedurally renamed quests.

Each world has six distinct situations. The shared director supplies only
eligibility, time, confirmation and persistence, never unwritten AI prose.
Fields: family, title, invitation, investigated fact, prepared approach/result,
        direct approach/result. Canon appointments retain their own calendar.
"""
PEOPLE = {
 'Naruto':'Iori Senda', 'One Piece':'Pella Reed', 'Bleach':'Haru Mizuse',
 'Hunter x Hunter':'Neris Voss', 'Jujutsu Kaisen':'Emi Otsuka', 'Overgeared':'Sella Forge',
 'Solo Max-Level Newbie':'Han Mira', 'Reincarnated as a Slime':'Tessa Brook', 'Custom World':'Corin Vale',
}
STORIES = {
 'Naruto': [
 ('training','The Unbroken Target','A practice organizer invites you to a control exercise. The goal is to move a suspended target without tearing its paper seal.',
  'The exercise rewards timing, not raw output. A steadier partner can call the moment to release.',
  'Coordinate the exercise','You finish the paired exercise without tearing the seal. The organizer offers to exchange future field reports.',
  'Practice the timing alone','You slow the exercise down and identify the point where your timing slips. You leave with a practical field routine, not a new jutsu.'),
 ('exploration','The Forgotten Signal Post','Your route work brings an old civilian signal post to your attention. Its message board is still being used.',
  'The warnings describe washed-out footpaths, not enemy movements. Residents have been keeping them current.',
  'Help maintain the reports','You record the residents’ corrections and agree on a reliable point of contact. Travelers can ask for current local reports.',
  'Map the safe approach','You mark an approach for your own next journey. You do not claim to have secured the whole road.'),
 ('work','Two Copies of a Delivery','A local supplier asks you to compare two delivery slips before a civilian order is dispatched.',
  'A copied destination, rather than a forged seal, caused the discrepancy. No sabotage has been established.',
  'Reconcile both records','The correct order reaches the dispatch desk. The supplier is grateful for the careful check and becomes a local contact.',
  'Return the uncertain order','You return the mismatched paperwork rather than guessing. The supplier gives you verified route notes while the order is checked.'),
 ('social','An Evening at the Practice Yard','People you have been spending time around invite you to an informal meal after practice.',
  'The gathering is simply a chance to get acquainted. Nobody is testing your loyalty or asking for a mission.',
  'Help host the meal','You help set out the meal and spend the evening listening. The organizer remembers your company and welcomes another visit.',
  'Join for a short visit','You share a meal, exchange practical travel advice and leave when you need to. There is no penalty for keeping the visit short.'),
 ('community','A Place Between Missions','Residents ask whether a disused public room could serve as a rest stop for messengers and relief volunteers.',
  'Permission to use the room is already available. Volunteers have supplies, but need help organizing shifts.',
  'Organize the rest station','You help open the volunteer rest station. Ordinary recovery here improves; you gain no ownership or official rank.',
  'Coordinate a smaller rota','You arrange a manageable volunteer rota without opening a permanent station. Its organizer becomes a useful local contact.'),
 ],
 'One Piece': [
 ('training','The Rolling Deck Drill','A local instructor offers a balance drill on a moored practice platform. No Haki awakening is promised.',
  'The platform shifts under uneven weight. Calling each movement lets a partner compensate before the next step.',
  'Practice as a pair','You complete the balancing drill together. The instructor offers to share local sailing reports when you prepare a journey.',
  'Work through the drill alone','You learn where your footing fails as the platform rolls. The practice improves your preparation, not your Devil Fruit powers.'),
 ('exploration','The Tide Marks','Route surveys reveal conflicting tide marks near a landing used by small boats.',
  'One mark belongs to an older shoreline. A local boatkeeper can identify which approach is still usable.',
  'Check the landing together','You verify the approach with the boatkeeper. You now have someone local to ask before sailing.',
  'Record a cautious approach','You record the usable landing and its limits for your own journey. This does not grant passage through an unknown sea route.'),
 ('work','Cargo Without a Claimant','A delivery organizer asks for help with an ordinary crate whose receipt has come loose.',
  'The crate is food, not hidden treasure. Matching its packing marks to the vendor’s ledger can identify the owner.',
  'Trace the proper owner','The vendor receives the missing provisions. The organizer offers reliable local reports in return for your help.',
  'Leave it with the custodian','You record where the crate was found and leave it with the established custodian. You take only the route information offered to you.'),
 ('social','A Seat at the Long Table','Local travelers invite you to a shared supper where crews trade ordinary stories and useful contacts.',
  'No recruitment oath is involved. One organizer is looking for dependable people to exchange port reports with.',
  'Stay and exchange stories','You enjoy the evening and establish a friendly port contact. No one joins your crew without a separate agreement.',
  'Exchange sailing notes','You compare current port reports and head back to your own plans. The gathering ends without a manufactured conflict.'),
 ('community','The Storm Shelter','People working around the landing propose turning an already permitted store room into a public storm shelter.',
  'The community has the space and basic materials. The missing piece is an organized volunteer schedule.',
  'Help open the shelter','The public shelter opens with local volunteers. Resting here becomes more effective; the island does not become your territory.',
  'Organize emergency contacts','You connect the volunteers and boatkeepers without establishing a permanent shelter. A local organizer remains available for reports.'),
 ],
 'Bleach': [
 ('training','The Bell Without a Sound','A local practice organizer invites you to cross a courtyard without disturbing suspended bells.',
  'The task concerns footwork and awareness. A partner can identify which steps disturb the lines.',
  'Practice with a spotter','You refine the exercise with a spotter and establish a local practice contact. No release state or rank changes.',
  'Review your own route','You identify a quieter route across the courtyard and prepare a more deliberate routine for your next outing.'),
 ('exploration','The Misplaced Boundary Marker','Your surveys lead to a marker that no longer matches a well-used district path.',
  'Local residents moved the path around unsafe masonry. The marker was never updated; no secret realm passage is involved.',
  'Verify the path with residents','You help reconcile the local route report. A resident agrees to keep you informed about this path.',
  'Record the safe detour','You record the detour for your own use. You do not claim access to a sealed district or another realm.'),
 ('work','The Undelivered Bundle','A local courier asks you to identify the destination of a bundle of ordinary relief supplies.',
  'Two households share a similar address. Checking the collection register avoids delivering to the wrong one.',
  'Check the register together','The bundle reaches the correct collection point. The courier becomes a dependable local contact.',
  'Return it for verification','You return the uncertain bundle with a clear note. The courier provides current district reports while the address is checked.'),
 ('social','Tea After the Rounds','People you have come to know locally invite you to sit with them after the day’s work.',
  'The conversation is about daily life, not a concealed test or a captain’s secret orders.',
  'Spend the evening together','The evening ends with a warmer acquaintance and an invitation to return. No new obligation is imposed.',
  'Share a brief conversation','You exchange ordinary news and useful route information before leaving. The short visit is welcomed on its own terms.'),
 ('community','Room for the Night','Local volunteers have permission to reopen a vacant room as a rest point for couriers and residents.',
  'A caretaker has agreed to supervise the room. A workable cleaning and supply rota is still needed.',
  'Help establish the rest point','The supervised rest point opens. Ordinary recovery improves here, without creating a new division or granting you authority.',
  'Support the caretaker’s rounds','You help the caretaker organize smaller deliveries instead. They remain a local contact for district reports.'),
 ],
 'Hunter x Hunter': [
 ('training','The Observation Game','A practice organizer invites you to identify which objects moved while your attention was elsewhere.',
  'The exercise tests observation. It neither requires Nen nor reveals another person’s concealed Hatsu.',
  'Compare observations with a partner','Together you identify the mistaken assumptions in each account. The organizer offers future expedition reports.',
  'Repeat with a written record','You replace guesses with a careful record and leave with a useful preparation routine, not a newly acquired ability.'),
 ('exploration','Tracks Beside the Survey Line','Your route work leads to animal tracks crossing a proposed survey path.',
  'The tracks belong to ordinary local wildlife. A field observer can help route visitors around the nesting area.',
  'Plan around the nesting ground','You verify the detour with the observer and establish a local expedition contact.',
  'Record and leave the site alone','You mark the sensitive area in your own notes and leave it undisturbed. Nothing attacks merely because you investigated.'),
 ('work','The Auction Description','An appraiser asks for a second look at an ordinary item’s conflicting catalogue descriptions.',
  'The physical marks support one description but not the claimed expedition history. The discrepancy is not proof of a criminal conspiracy.',
  'Document the limited finding','The catalogue is corrected to match the evidence. The appraiser becomes a useful contact for local reports.',
  'Decline to authenticate it','You withhold an endorsement and record what remains unknown. The appraiser shares practical expedition notes without demanding agreement.'),
 ('social','A Table of Specialists','Local field workers invite you to a meal where each person describes a different kind of expedition work.',
  'They are exchanging experience, not offering Hunter licenses or knowledge of secret techniques.',
  'Help arrange future introductions','You establish a local point of contact for field reports. Choosing a specialty remains your own decision.',
  'Listen and compare methods','You leave with practical preparation notes and a clearer picture of the work. No compulsory assignment follows.'),
 ('community','The Field Rest Point','An expedition support group has permission to maintain a small rest point for returning field workers.',
  'Supplies are already pledged. The group needs a manageable rota rather than a powerful patron.',
  'Organize the field shelter','The rest point opens and improves ordinary recovery here. Its community remains independent.',
  'Arrange report exchanges','You connect returning workers with the support group. An organizer becomes your local information contact.'),
 ],
 'Jujutsu Kaisen': [
 ('training','The Blind Corner Exercise','A practice organizer offers a drill in reading movement around obstructed corners.',
  'The drill uses ordinary movement and agreed signals. It does not require a new innate technique or reward a random Black Flash.',
  'Run the exercise with a partner','You coordinate the drill and establish a local practice contact who can share field reports.',
  'Review your positioning','You identify the exposed corner and prepare a safer approach. Your innate technique is unchanged.'),
 ('exploration','The Locked Side Exit','Your surveys bring attention to a side exit marked as usable on an old local evacuation diagram.',
  'The building manager confirms the exit is closed for repairs. An ordinary signage error explains the discrepancy; no curse has been confirmed.',
  'Verify the alternative exit','You check the alternative with the manager. A reliable local reporting contact is established.',
  'Record the access restriction','You update your own preparation notes and leave the closed route alone. The record does not invent a supernatural cause.'),
 ('work','The Miscounted Equipment','A local equipment organizer asks you to check a mismatch between the return sheet and an ordinary supply box.',
  'The missing items were transferred to another desk with a duplicate receipt. No cursed tool is being awarded.',
  'Reconcile the return sheets','The equipment records now agree. The organizer offers to share practical local reports.',
  'Report only the verified count','You provide the count you can verify and leave the remaining paperwork to its owner. You receive useful preparation notes, not secret equipment.'),
 ('social','An Ordinary Afternoon','People you have been helping invite you to a quiet break away from work.',
  'Nobody has reported a threat. The invitation is an ordinary chance to spend time together.',
  'Help arrange the gathering','You enjoy the afternoon and establish a warmer local connection. The day ends without a compulsory crisis.',
  'Stop by briefly','You exchange everyday news and practical local advice. Leaving early creates no penalty.'),
 ('community','A Waiting Room That Works','Volunteers have approval to reopen a public rest room used during local relief work.',
  'The room needs an agreed supply rota. It is not a barrier, and opening it will not automatically repel curses.',
  'Organize the relief room','The room becomes a supervised place to rest. Ordinary recovery improves here; supernatural injuries remain untreated.',
  'Coordinate volunteer contacts','You connect the available volunteers without opening a permanent room. Their organizer becomes a local reporting contact.'),
 ],
 'Overgeared': [
 ('training','The Weighted Practice Blade','A practice organizer offers a balance exercise with a deliberately uneven training weapon.',
  'The exercise tests adjustment and timing, not eligibility for a legendary class.',
  'Compare techniques with a partner','You finish a productive paired session. The organizer becomes a local contact; no class is granted.',
  'Record a personal drill','You develop a repeatable preparation drill using ordinary equipment. Your class progression remains tied to actual accomplishments.'),
 ('exploration','The Surveyor’s Spare Copy','Your route work catches the attention of a surveyor comparing an old track with a recently used detour.',
  'The old track crosses damaged ground. The surveyor can verify a legal detour without granting access to an unexplored dungeon.',
  'Verify the detour together','You establish a useful survey contact and leave the unsafe track clearly identified.',
  'Keep a conservative route record','You record the known detour for your next journey without claiming to have cleared nearby monsters.'),
 ('work','The Workshop’s Trial Order','A workshop invites you to help check an ordinary trial order before it promises a larger contract.',
  'The customer needs consistent fittings, not a legendary item. The workshop already holds the materials and permission to use them.',
  'Help check the finished order','You help the workshop verify the order. Its organizer offers ongoing local reports, not an unearned legendary class.',
  'Document the specification','You clarify the requested specification and leave production to the workshop. You receive practical route and supply notes.'),
 ('social','A Guildless Supper','Independent workers invite you to a supper where people can meet without joining a guild.',
  'No recruitment contract is attached. The organizer wants a dependable local circle for exchanging information.',
  'Help build the local circle','You establish a friendly local contact. Existing guild memberships remain unchanged.',
  'Exchange notes and leave','You compare practical travel advice, then return to your plans. No guild rivalry is invented.'),
 ('community','The Shared Workroom','Local workers have permission to use a vacant room for breaks and community relief.',
  'Materials are available. The remaining need is a fair schedule and someone to coordinate the volunteers.',
  'Organize the public rest room','The shared rest room opens and improves ordinary recovery here. It is not your property and generates no passive income.',
  'Set up a smaller work circle','You connect the volunteers without opening a permanent room. The coordinator becomes a local contact.'),
 ],
 'Solo Max-Level Newbie': [
 ('training','The Moving Marker Drill','A local climber proposes a timing exercise with ordinary movable markers inside the currently accessible area.',
  'The drill helps coordinate movement. It does not satisfy an unknown ability-copy condition.',
  'Practice coordinated movement','You finish the drill together and establish a local climber contact for current-floor reports.',
  'Record your own timing','You prepare a repeatable routine. No copied ability, title or unearned floor clearance is granted.'),
 ('exploration','Yesterday’s Route Note','Your surveys expose a disagreement between a posted route note and a recent climber’s account.',
  'The account concerns a route within your current floor. It says nothing reliable about locked or unreached floors.',
  'Verify the local route together','You establish a current-floor reporting contact. The verified route does not open another floor.',
  'Mark the uncertainty','You preserve the uncertain section in your own preparation notes instead of declaring it safe.'),
 ('work','The Camp Supply Split','A camp organizer asks you to compare ordinary supply allocations before the next collection.',
  'Two lists count the same delivery. The supplies exist, but cannot be distributed twice.',
  'Correct the duplicate allocation','You help the organizer reconcile the lists. They offer current-floor reports as a local contact.',
  'Report the verified stock','You provide the count you verified and decline to promise nonexistent supplies. Your next journey can use the camp’s practical notes.'),
 ('social','A Break Between Attempts','Nearby climbers invite you to a quiet meal after their routine work.',
  'The gathering carries no hidden system reward. People want to compare experiences without revealing private abilities.',
  'Help keep the group connected','You establish a friendly current-floor contact. Nobody becomes your subordinate without agreement.',
  'Exchange ordinary route advice','You leave with useful local preparation notes. The system does not invent an achievement for having a conversation.'),
 ('community','A Rest Point on This Floor','Local climbers have found permission and supplies for a modest rest point in the accessible settlement.',
  'It can support ordinary recovery. It cannot stop the floor deadline or bypass the floor’s rules.',
  'Organize the rest point','The rest point opens on this floor and improves ordinary recovery here. The floor deadline continues unchanged.',
  'Coordinate the camp contacts','You connect existing helpers without opening a permanent rest point. Its organizer offers current-floor reports.'),
 ],
 'Reincarnated as a Slime': [
 ('training','The Shared Practice Circle','A practice organizer invites people with different bodies and fighting styles to compare ordinary movement drills.',
  'The drill can be adapted without naming anyone, transferring magicules or granting evolution.',
  'Coordinate an adapted exercise','You complete the shared practice and establish a local contact. No participant changes species or allegiance.',
  'Prepare an individual routine','You develop a practical routine suited to your own movement. No skill synthesis occurs without its actual requirements.'),
 ('exploration','The Seasonal Crossing','Your surveys draw attention to a river approach whose usefulness changes with the water level.',
  'A local observer has recent measurements. Their advice concerns this crossing, not a guarantee that the whole region is safe.',
  'Verify the crossing together','You establish a local route contact and preserve the limits of what was observed.',
  'Record a conservative approach','You prepare your next journey around the verified approach without claiming ownership of the river.'),
 ('work','The Cartwright’s Request','A local cartwright asks for help checking a shared shipment of ordinary replacement fittings.',
  'The fittings are sound, but two cart owners have exchanged collection slips. Their existing agreement can resolve it.',
  'Match the fittings to the orders','The cartwright can complete the correct deliveries. They become a useful local contact.',
  'Return the disputed slips','You return the mismatched records for verification and receive practical local route notes. No accusation is invented.'),
 ('social','A Meal with New Neighbors','Local residents invite you to a shared meal where several communities are introducing themselves.',
  'An invitation is not a naming ceremony or a pledge of loyalty. People want to become acquainted.',
  'Help welcome the guests','You establish a friendly local connection. No magicules are spent and no automatic subordination occurs.',
  'Join the conversation briefly','You compare ordinary travel advice and return to your plans. The guests accept the brief visit without offense.'),
 ('community','A Common Rest House','Residents have agreed to provide a public room and basic materials for a shared rest house.',
  'A joint volunteer rota will let it operate without placing one community under another’s rule.',
  'Organize the joint rota','The public rest house opens. Ordinary recovery improves here; ownership and international recognition do not change.',
  'Connect the existing helpers','You form a smaller coordination circle instead. Its organizer becomes a local reporting contact.'),
 ],
 'Custom World': [
 ('training','The Partner Exercise','A local practice organizer invites you to a timing exercise with ordinary equipment.','The task rewards coordination rather than raw power.','Practice together','You establish a local practice contact without gaining an unearned ability.','Prepare a personal routine','You leave with a practical routine for your next journey.'),
 ('exploration','The Overlooked Detour','Your surveys reveal an outdated sign on a familiar route.','Residents can identify a recently used detour.','Verify the detour','You establish a local reporting contact.','Record the uncertainty','You record the detour and its limits for your own preparation.'),
 ('work','The Unmatched Receipt','A local supplier asks you to compare two ordinary delivery records.','A duplicate destination explains the mismatch; no sabotage is established.','Reconcile the records','The supplier becomes a local contact after the records are corrected.','Return the uncertain order','You avoid guessing and receive verified local route notes.'),
 ('social','A Place at Supper','People you have spent time around invite you to a simple shared meal.','The invitation carries no test or hidden obligation.','Help host the gathering','You establish a warmer local connection.','Join for a brief visit','You enjoy the visit and exchange useful preparation notes without taking on an obligation.'),
 ('community','The Public Rest Room','Volunteers have permission and materials to reopen a community rest room.','An agreed volunteer schedule is still needed.','Organize the rota','The rest room opens and improves ordinary recovery here without granting ownership.','Connect the volunteers','You establish a local contact without opening a permanent rest room.'),
 ],
}

INVESTIGATIONS = {
 'Naruto':('The Borrowed Seal','A local courier asks for help with a relief dispatch that someone tried to seize.','The dispatch concerns civilian supply stops. The courier witnessed the attempt but cannot identify who hired the attackers.','rogue supply thieves',60),
 'One Piece':('The Missing Dock Register','A dockworker offers testimony about raiders taking provisions from local fishing boats.','The witness can identify the stolen crates, but has no evidence of a Marine or government conspiracy.','dockside provision raiders',45),
 'Bleach':('The Interrupted Relief Route','A courier reports a minor Hollow attacking a local relief route and asks for help protecting the next withdrawal.','The sighting is recent and local. It is not evidence of an Arrancar invasion or a captain’s involvement.','minor Hollow',65),
 'Hunter x Hunter':('The Expedition Witness','A returning field worker reports that armed scavengers took an expedition’s records.','The worker can identify the records. No opponent’s Nen ability has been observed or inferred yet.','armed relic scavengers',50),
 'Jujutsu Kaisen':('The Empty Stairwell','A field assistant reports a weak curse near an evacuation stairwell and asks for help securing a civilian withdrawal.','The assistant saw the manifestation near the stairs. Its origin and governing rule have not been established.','low-grade stairwell curse',55),
 'Overgeared':('The Supply Wagon Witness','A wagon keeper reports brigands intercepting ordinary workshop deliveries outside the settlement.','The keeper can identify the stolen shipment. Nothing links the thieves to a legendary class quest.','workshop supply brigands',45),
 'Solo Max-Level Newbie':('The Camp Store Ambush','A climber reports scavengers threatening a supply withdrawal within the current floor.','The report names only a local group. It reveals no administrator secret or hidden ability-copy condition.','current-floor camp scavengers',50),
 'Reincarnated as a Slime':('The Interrupted Caravan','A local guide reports raiders threatening travelers approaching the settlement.','The guide witnessed the threat. The raiders’ employer is unknown; no neighboring nation has been implicated.','local caravan raiders',50),
 'Custom World':('The Witness at the Waystation','A courier reports raiders threatening a small relief group.','The courier witnessed the attack, but cannot identify anyone behind the local group.','local relief raiders',45),
}

def catalog(world):
    rows=[dict(zip(('family','title','invitation','finding','prepared_label','prepared_result','direct_label','direct_result'),r),
                 id=f"original:{world}:{r[0]}", author=PEOPLE[world]) for r in STORIES.get(world,[])]
    if world in INVESTIGATIONS:
        title,invitation,finding,enemy,power=INVESTIGATIONS[world]
        rows.append(dict(id=f'original:{world}:investigation',family='investigation',title=title,invitation=invitation,
            finding=finding,author=PEOPLE[world],prepared_label='Submit the verified account',
            prepared_result='You deliver the account through the local reporting contact. The report is received, not magically resolved: no enemy has been defeated and no territory changes hands.',
            direct_label='Protect the withdrawal',direct_result='The relief group completes its withdrawal under your protection. The threat has not been defeated or driven out of the region.',enemy=enemy,power=power))
    return rows
