"""Player-facing release notes shown once per browser/account and version."""

RELEASE_NOTES = {
    "3.51.0": {
        "title": "Choose or Write Any Action",
        "summary": "A world-aware action picker makes common choices quick without restricting the freeform game.",
        "highlights": [
            {"title": "Actions are easier to find", "example": "Open Choose an Action for relevant people, training, travel, work, group, combat, personal and world-specific choices."},
            {"title": "Rest is always available", "example": "Rest, sleep, meals, treatment, relaxation, reflection and equipment care are available without rewriting them every turn."},
            {"title": "People are directly interactive", "example": "Select a portrait in Relationships to talk, spend time, train, help, give a gift, spar or issue a valid instruction."},
            {"title": "Long-running plans stay clear", "example": "An ongoing care or protection choice is written as a standing instruction that persists until canceled or circumstances stop it."},
            {"title": "Freeform play is unchanged", "example": "Write Anything returns to the normal composer, where any reasonable world-valid action can still be described and edited."},
            {"title": "No extra AI charge", "example": "The menu, recommendations, favorites and recent actions are assembled locally; only the normal turn resolution uses the GM."},
        ],
    },
    "3.50.0": {
        "title": "Faces Across the World",
        "summary": "Approved portraits now identify people throughout the interface without adding more menus or crowding existing screens.",
        "highlights": [
            {"title": "Conversations have a face", "example": "NPC chats, incoming messages and conversation suggestions show the speaker in the row you already use."},
            {"title": "Groups are easier to scan", "example": "Crew, squads, organizations and relationships use compact portraits while preserving every existing position, power and relationship detail."},
            {"title": "Battles identify everyone", "example": "The tactical turn strip, battlefield pieces and target list use the same approved form-aware art, including active transformations."},
            {"title": "Events show who matters", "example": "Advisor comparisons, relationship changes, major events and timeline entries show up to three relevant faces instead of adding another panel."},
            {"title": "Locations feel inhabited", "example": "Selecting a map location previews known people present there while respecting what the campaign has actually recorded."},
            {"title": "No misleading stand-ins", "example": "If an approved portrait is unavailable, the interface shows readable initials rather than reusing the wrong character art."},
        ],
    },
    "3.49.0": {
        "title": "One Piece Canon Power Library",
        "summary": "One Piece canon powers now resolve from local presets, with richer Haki mechanics and a dedicated Conqueror's Haki victory cut-in.",
        "highlights": [
            {"title": "Canon powers are ready locally", "example": "Known Devil Fruits, named techniques, transformations and fighting styles already know their range, affected tiles, cost and visual treatment instead of asking the AI to design them during battle."},
            {"title": "Haki applications stay distinct", "example": "Future Sight, Hardening, Emission, Internal Destruction and Conqueror's Coating provide different effects and remain gated by the character's actual mastery and recorded unlocks."},
            {"title": "Conqueror's victories feel decisive", "example": "Winning through the Overwhelm button with Conqueror's Haki triggers a black-red pressure and lightning cut-in; resisted attempts do not play the victory animation."},
            {"title": "No accidental future powers", "example": "The catalog records canon ownership and introduction arc, but a technique appears for use only when the campaign says that character has learned or awakened it."},
            {"title": "Original powers remain welcome", "example": "A player-created Devil Fruit is still unique, then its applications are classified locally into the same combat vocabulary without needing an extra AI mechanics call."},
        ],
    },
    "3.48.0": {
        "title": "Tactical Battles: Naruto & One Piece",
        "summary": "Narrative encounters in Naruto and One Piece can now open a server-authoritative grid battle with movement, aimed techniques, transformations, status enforcement and world-specific rules.",
        "highlights": [
            {"title": "Move and aim on the battlefield", "example": "Move horizontally or vertically without spending your attack, choose a learned move, preview its exact affected tiles, then launch it in the chosen direction."},
            {"title": "Naruto techniques keep their identity", "example": "Shadow Clones occupy the selected open tile, Rasengan uses its own range and effect, summons require established contracts, and named forms activate without consuming the attack action."},
            {"title": "One Piece powers follow their rules", "example": "Devil Fruit applications, Haki, Zoan forms, Logia counters, Sea-Prism Stone, Geppo and Room: Shambles behave differently instead of becoming generic attacks."},
            {"title": "Strength comes from the campaign", "example": "A Marine captain, bandit or canon fighter enters with strength supported by their role and established feats rather than automatically scaling to the player."},
            {"title": "Phone-ready combat", "example": "The same board supports tap targeting, clear out-of-range feedback, readable stamina or chakra, world-specific styling, and no typed actions until the battle is resolved."},
            {"title": "Safe outcomes and old saves", "example": "Older Haki records migrate automatically, retries cannot replay an accepted move, and battle receipts return to the Chronicle without inventing loot, bounties or news coverage."},
        ],
    },
    "3.47.0": {
        "title": "Crews, Command Chains & Lasting Legacies",
        "summary": "World-specific full rosters, narrative membership, independent NPC development and agreed succession. Existing campaigns benefit without restarting.",
        "highlights": [
            {"title": "Your whole group, wherever they are", "example": "Pirate Crew, Marine Squad, Shinobi Organization and other world-native rosters show the group's name, members, positions and combat power—even when a member is away. Estimates are clearly marked."},
            {"title": "Commands follow real authority", "example": "A medic who reports to your deputy receives your order through that chain; an independent ally does not become a subordinate just because they are friendly."},
            {"title": "Members develop independently", "example": "A crewmate practicing a known combat discipline improves during a long voyage from their own stats, time and mentor. Studying medicine builds expertise without inflating combat power."},
            {"title": "Recruitment and departure mean something", "example": "An invited navigator stays an applicant until they agree to join. Recruitment terms and reasons for departure remain in their record; leaving the current scene does not remove membership."},
            {"title": "Family, apprentices and succession", "example": "Children age over elapsed campaign years, mentors and family ties are remembered, and an accepted successor takes over after actual death or voluntary retirement—not an automatic character switch."},
            {"title": "Works with existing campaigns", "example": "Established affiliations and rosters migrate automatically. The phone's More menu opens the same full group roster; NPC calculations do not require an extra AI request."},
        ],
    },
    "3.46.0": {
        "title": "Better Memories, Faithful Commands & Short Chapters",
        "summary": "Short narrative recaps, more relevant GM context, safer retries, and corrections directly from the Chronicle. Existing campaigns benefit too.",
        "highlights": [
            {"title": "Chapters read like a story", "example": "A chapter recalls rebuilding a clinic, securing medicine and training through winter in one short paragraph, rather than pages of repeated actions and system lists."},
            {"title": "Groups and follow-up orders", "example": "Tell my guards to protect the children reaches established subordinate guards; have them continue refers back to that group without guessing among unrelated NPCs."},
            {"title": "Connected campaign memories", "example": "Asking about your orphanage also brings its caretaker and funding promise into the GM's focused context."},
            {"title": "Relevant reasons for reactions", "example": "Knowing you visited a harbor does not justify knowing about a secret technique. Refusals and complications must cite a relevant established fact."},
            {"title": "Completed stories stay completed", "example": "A finished clinic remains a useful accomplishment; reopening its original problem requires a new evidenced cause, not an automatic new crisis."},
            {"title": "Fewer false breakthrough alarms", "example": "Discussing Bankai, remembering an old achievement, or describing an NPC's awakening no longer automatically demands a new player ability."},
            {"title": "Retry without starting from scratch", "example": "After a failed application, retry reuses settled dice and cached response stages when the action and campaign still match; repaired text is checked before committing."},
            {"title": "Correct a Chronicle entry", "example": "Choose Correct this, preview the proposed fact and any mechanical changes, then explicitly apply it. Existing skill metadata is preserved."},
            {"title": "Long-campaign regression coverage", "example": "Tests advance calendars and reload saves across all nine worlds while checking retirement, death, acquired skills, chapter length and settled projects."},
        ],
    },
    "3.45.1": {
        "title": "NPC Chat on Mobile",
        "summary": "Reach your NPC conversations directly from the phone's More menu.",
        "highlights": [
            {"title": "More → NPC Chat", "example": "Tap More, then NPC Chat to read messages, choose a contact, and reply using the existing Chats & Contacts screen."},
        ],
    },
    "3.45.0": {
        "title": "A More Consistent GM",
        "summary": "Better command fidelity, evidence-backed reactions, current campaign memory and outcome checks, including existing saves.",
        "highlights": [
            {"title": "Conditional actions stay conditional", "example": "Watch him, but do not attack unless he threatens Konan no longer counts as immediately committing violence."},
            {"title": "Subordinates follow the actual order", "example": "A loyal subordinate delivers your sealed invitation without replacing your goal; refusal or deviation needs established supporting evidence."},
            {"title": "Reactions need an information path", "example": "A distant ruler cannot react using an invented messenger, and a report must arrive before its recipient responds."},
            {"title": "Narration agrees with rewards", "example": "A learned technique needs recorded mechanics; a refused purchase cannot award its item. Explicit recovery removes a condition instead of adding it again."},
            {"title": "Current facts override old summaries", "example": "A former captain keeps their history without regaining their old authority; a changed relationship informs the next conversation."},
            {"title": "More individual NPC conversations", "example": "Dialogue receives the contact's goals, loyalties, experiences and knowledge. Thanks or uncomplicated support are valid responses."},
            {"title": "Quieter long-skip routine", "example": "Routine training can share one progress section, while breakthroughs and real decisions retain their own updates."},
            {"title": "Repairs preserve valid outcomes", "example": "When a check finds a contradiction, one repair receives the original draft. A still-invalid result is not applied; ordinary valid turns need no extra call."},
            {"title": "Existing-save and multi-turn checks", "example": "The same rules apply after loading an older campaign. Tests follow a hidden skill through acquisition, export/import/load, conversation and use across every world."},
        ],
    },
    "3.44.3": {
        "title": "A More Causal and Efficient Game Master",
        "summary": "The GM now interprets intent locally, limits unsupported complications, respects information and time boundaries, chooses relevant examples, and reliably mirrors narratively earned Dōjutsu into Naruto's dedicated panel.",
        "highlights": [
            {"title": "Actions resolve before reactions", "example": "A successful diplomatic or strategic action lands first; independent characters respond afterward from their own motives instead of retroactively making the action fail."},
            {"title": "Complications need a cause", "example": "Ordinary success can stay positive, while a setback must point to a witnessed offense, real cost, failed roll, existing enemy, or another established reason."},
            {"title": "One ordinary complication at most", "example": "A routine turn no longer piles suspicion, a new enemy, a random cost, and a future threat onto the same successful action."},
            {"title": "Local intent and timing controls", "example": "Targets, methods, duration, standing instructions, and lethality are extracted before the GM writes, and a Moment stops at the next meaningful decision."},
            {"title": "Visible sustained training", "example": "A month of focused practice arrives with a local progression expectation, while the existing deterministic growth engine still calculates the actual gains."},
            {"title": "NPC knowledge is enforced", "example": "A reaction must identify how that person learned the fact—witness, conversation, message, report, rumor, research, or an ability."},
            {"title": "Better Advisor estimates", "example": "Named campaign characters without numeric sheets receive a current world-role estimate rather than a refusal or a generic low benchmark."},
            {"title": "Relevant liked-turn examples", "example": "A liked social scene teaches a later negotiation; it is no longer randomly inserted into an unrelated battle or training turn."},
            {"title": "Distinct next moves", "example": "Suggestions are locally deduplicated, use different approaches, reject unknown contacts, and do not tell you to resume a finished fight or travel where you already are."},
            {"title": "Narrative Sharingan recovery", "example": "If a Sharingan was gained or used during play but only existed in the Chronicle or skill list, the Dōjutsu panel repairs itself with its stage, applications, limits, counters, and growth path."},
            {"title": "Read new turns from the beginning", "example": "After Advance, the Chronicle lands on the first new update instead of auto-scrolling past the whole result to the bottom."},
            {"title": "Readable Naruto rolls", "example": "Success and failure pills on the parchment scroll now use dark ink, solid fills, and clear borders instead of pale mint text."},
            {"title": "Safer malformed-response handling", "example": "String recipients and malformed causal or knowledge fields are normalized before they can trigger another object-has-no-attribute error."},
        ],
    },
    "3.44.2": {
        "title": "Combat Applications and Clearer Campaign Updates",
        "summary": "Named moves inside broader abilities now work in combat, incoming messages stay grounded in what the sender could know, and narrative assignments no longer repeat empty boilerplate.",
        "highlights": [
            {"title": "Every established move is usable", "example": "Celestial Ember now exposes Flame Flight, Fiery Shield, and Ember Strike as separate combat choices without cluttering the Journal."},
            {"title": "Legacy combat tags repair themselves", "example": "Ignition Kick is recognized as an offensive move even if an older save incorrectly labeled it Utility and non-combat."},
            {"title": "Application-specific mechanics", "example": "Fiery Shield creates a barrier, Flame Flight grants movement advantage, and Ember Strike deals damage instead of all inheriting one generic effect."},
            {"title": "Grounded incoming messages", "example": "Konan can report on her own operation, while an unrelated village no longer sends fake quotes about private events it could not know."},
            {"title": "Canon-aware comparisons", "example": "Minato and other famous shinobi use world-scale benchmarks instead of being mistaken for a generic Chūnin."},
            {"title": "Existing message cleanup", "example": "Older locally generated messages lose the redundant 'a messenger arrives from…' wrapper when the campaign is loaded."},
            {"title": "Concise narrative assignments", "example": "Assignments omit 'Current direction: None,' repeated action text, and empty danger notices, leaving only meaningful context."},
            {"title": "Mobile combat verified", "example": "The complete ability list was selected and Fiery Shield resolved successfully in a phone-sized browser with no console errors."},
            {"title": "Clean combat narration", "example": "Combat logs show 'Fiery Shield' instead of leaking the internal parent/application selection ID."},
        ],
    },
    "3.44.1": {
        "title": "Reliable Economy and Poneglyph Chronicle",
        "summary": "Money changes are now auditable and exact, recurring expenses become payable obligations instead of negative balances, and One Piece turns arrive on the approved anime-style Poneglyph stone.",
        "highlights": [
            {"title": "Exact world currencies", "example": "A 0.5 Gold Coin purchase in the Slime world now deducts the correct Silver/Copper equivalent instead of becoming free."},
            {"title": "Money history", "example": "Purchases, income, expenses, and payments appear in a compact Bag ledger with the reason for every change."},
            {"title": "Payable obligations", "example": "Rent or wages that exceed available cash leave the balance at zero and create an outstanding obligation the player can pay later."},
            {"title": "Secondary-currency shops", "example": "Arena tokens, guild points, and other distinct currencies can price and purchase their own items without spending the primary balance."},
            {"title": "Reusable purchases stay useful", "example": "Bought equipment preserves its effect, rating, category, and restrictions when it enters the Bag."},
            {"title": "Narrative-only economies protected", "example": "Bleach and JJK cannot accidentally acquire a permanent money meter or price-gated offers from an AI patch."},
            {"title": "Wealth separated from power", "example": "Starting as immeasurably strong no longer silently creates extra money unless the background also establishes wealth."},
            {"title": "One Piece Poneglyph Chronicle", "example": "Each One Piece turn now sinks into place as a bright cel-shaded blue stone with readable carved-style lettering."},
        ],
    },
    "3.44.0": {
        "title": "Causal GM and World-Native Character Sheets",
        "summary": "Actions resolve more directly, AI jobs use smaller focused prompts, oversized campaigns recover automatically, and every world receives its approved Attributes design plus bundled canon portrait art.",
        "highlights": [
            {"title": "Causal outcomes", "example": "A successful private action can simply work; setbacks now require a concrete cause, believable awareness, a motive, and proportional scale."},
            {"title": "No manufactured drama", "example": "Solved problems stay solved, quiet victories are valid, and canon no longer bends an original campaign back toward the source plot."},
            {"title": "Focused AI jobs", "example": "Assessment, time planning, combat summaries, and continuity repair receive only the rules and context needed for their specific task."},
            {"title": "Long-campaign request recovery", "example": "Cloud requests are compacted to about 80k tokens and automatically retry near 60k if the provider rejects an oversized request."},
            {"title": "World-specific Attributes", "example": "Naruto uses a shinobi scroll, One Piece a bounty record, Overgeared a Satisfy window, Bleach a monochrome dossier, and every other world has its approved native treatment."},
            {"title": "Bundled canon portraits", "example": "Approved canon starts and supported transformations load from local art instead of spending an image-generation request."},
            {"title": "Cleaner Naruto pointers", "example": "The Naruto kunai cursor and spinning shuriken loading indicator now better match their source-world silhouettes."},
            {"title": "Full regression coverage", "example": "The patch passes 785 automated checks covering campaigns, worlds, combat, saves, mobile behavior, prompts, and UI contracts."},
        ],
    },
    "3.43.0": {
        "title": "Long Campaign Stability",
        "summary": "Long-running campaigns now repair stale bookkeeping before Advance, preserve complete standing plans, recover partial AI replies, and store history far more efficiently.",
        "highlights": [
            {"title": "Pre-Advance campaign health check", "example": "Before a turn begins, malformed deep state is repaired locally so an old save cannot crash before rollback protection starts."},
            {"title": "Stale goals retire cleanly", "example": "A training goal from dozens of turns ago is archived when its plan is no longer active instead of contaminating the current scene."},
            {"title": "Quests and scenes reconcile", "example": "Completed quests move to the archive, duplicates disappear, and the live scene follows the character's actual location."},
            {"title": "Stale combat closes itself", "example": "Combat cannot remain active with a defeated opponent, missing enemy, or incapacitated player and block every later action."},
            {"title": "Much smaller save snapshots", "example": "Undo checkpoints keep current facts but no longer repeat hundreds of old events and diagnostics in every copy."},
            {"title": "Deep schema repair", "example": "Malformed NPC dossiers, combatants, quest rows, histories, and nested containers are normalized with exact diagnostic paths."},
            {"title": "Actionable error IDs", "example": "An unexpected API failure returns a short support ID while preserving the campaign and recording the failing route and data shape."},
            {"title": "Partial AI replies survive", "example": "If a model returns updates or state changes without its main narrative field, the usable result is recovered without paying for another call."},
            {"title": "Hot, warm, and cold memory", "example": "Recent turns, chapter summaries, and verified archives are separated so the GM gets relevant history without resending the full save."},
            {"title": "Standing orders have a lifecycle", "example": "A multi-action plan keeps every unfinished instruction across Moments while completed, deferred, and replaced orders are tracked separately."},
            {"title": "Readable NPC development updates", "example": "Off-screen growth now distinguishes training progress, ongoing story movement, and an NPC approaching a decision instead of calling every goal an overdue commitment."},
        ],
    },
    "3.42.1": {
        "title": "Long-Campaign Advance Recovery",
        "summary": "Advance now accepts compact companion names correctly and automatically removes misplaced response-envelope data from NPC memories.",
        "highlights": [
            {"title": "String companions no longer block Advance", "example": "Campaigns with companions stored as names such as Emi Kuroda can prepare canon context and advance normally."},
            {"title": "NPC-memory namespace repaired", "example": "Misplaced fields such as elapsed time, quests, and completed actions are removed during import/load without deleting real NPC dossiers."},
            {"title": "Future corruption blocked", "example": "Malformed AI patches are filtered at the state boundary before unrelated response fields can enter NPC memories."},
            {"title": "Existing campaigns recover on load", "example": "Loading or importing the campaign applies the repair automatically; a new character is not required."},
            {"title": "Standing plans remain intact", "example": "A queued multi-action plan continues in its original order after the campaign is repaired."},
            {"title": "Real NPC histories are preserved", "example": "Relationships, knowledge, goals, and memories belonging to named characters survive the cleanup."},
            {"title": "Compact and structured companions coexist", "example": "Older name-only companions and newer detailed companion records can safely appear in the same campaign."},
            {"title": "Reported save shape is regression-tested", "example": "Automated coverage now prepares and resolves Advance from the same companion and standing-order layout as the affected turn-311 save."},
        ],
    },
    "3.42.0": {
        "title": "Resilient Turns and Deeper Campaign Continuity",
        "summary": "Turns now recover atomically from malformed AI output while active scenarios, combat stakes, milestones, messages, generated powers, costs, and long-campaign testing receive stronger local support.",
        "highlights": [
            {"title": "Failed turns cannot half-apply", "example": "If an Advance response crashes during processing, the campaign returns to the exact clean pre-turn state and keeps a safe Retry Failed Turn option."},
            {"title": "Broader AI-response repair", "example": "Compact events, updates, chats, assessment rows, and combatants are converted into usable structures before gameplay reads them."},
            {"title": "Active scenario memory", "example": "A continuing fight or major situation carries its cause, objective, stakes, location, and latest development into later GM and Advisor context."},
            {"title": "Smarter original-power uniqueness", "example": "Renaming a momentum-storage technique no longer makes it count as a different generated power."},
            {"title": "Long-campaign stability", "example": "The bounded Chronicle and prompt budgets keep old campaigns responsive without deleting their saved history."},
            {"title": "Clear combat context", "example": "Combat shows why it began, what ends it, and what is at risk above the action controls."},
            {"title": "More grounded messages", "example": "Known contacts can warn, check on, congratulate, or follow up based on the actual event and their relationship."},
            {"title": "World-native milestones", "example": "Shikai, bounties, Haki, Nen, grades, floor clears, Satisfy classes, and evolutions receive deduplicated setting-specific records."},
            {"title": "Per-turn AI cost visibility", "example": "Diagnostics now records the model, task, token use, and estimated cost of the latest narrated turn alongside session totals."},
            {"title": "Expanded free playtest matrix", "example": "Every built-in world is automatically checked for capability, progression, NPC, scenario, malformed-response, and transaction contracts without spending AI credits."},
        ],
    },
    "3.41.1": {
        "title": "Advance and Combat Hotfix",
        "summary": "Advance now safely accepts compact or malformed combat data instead of trapping the campaign behind a string-object error.",
        "highlights": [
            {"title": "Advance no longer stalls", "example": "An AI response such as enemy: Tunnel Guard is converted into a complete combatant record before the turn continues."},
            {"title": "Nested combat recovery", "example": "Malformed status, cooldown, log, contact, and message-delivery shapes are normalized before gameplay reads them."},
            {"title": "Existing campaigns repair themselves", "example": "Loading and advancing an affected save preserves the opponent's name and repairs the combat structure automatically."},
            {"title": "Opponent identity is preserved", "example": "A compact enemy name remains Tunnel Guard instead of becoming a generic Enemy during repair."},
            {"title": "Status lists are hardened", "example": "A compact Paralyzed status becomes a usable timed status record rather than breaking combat."},
            {"title": "Stale checks are harmless", "example": "Malformed legacy difficulty rows are ignored while valid actions still resolve."},
            {"title": "Messages cannot break Advance", "example": "Old contact and message-delivery values are repaired before reactive messages are processed."},
            {"title": "All v3.41.0 features retained", "example": "Autonomous companions, NPC development, ability history, downtime, recovery tools, and narrative Satisfy classes remain enabled."},
        ],
    },
    "3.41.0": {
        "title": "A World That Keeps Moving",
        "summary": "Long skips, companions, NPCs, abilities, messages, recovery, and Satisfy classes now develop through persistent local systems with less AI overhead.",
        "highlights": [
            {"title": "Dated multi-beat time skips", "example": "A month can show separate training, companion, communication, and world developments across the actual dates instead of one flattened result."},
            {"title": "Independent companion work", "example": "A companion assigned to maintain a shelter or investigate a lead can reach milestones while the player pursues something else."},
            {"title": "NPCs develop on their own", "example": "Recurring allies and rivals can train and grow from their own established goals without being scaled to the player."},
            {"title": "Ability evolution history", "example": "Opening a skill can show the applications and breakthroughs it has gained during this campaign."},
            {"title": "World-specific downtime", "example": "Bleach skips include division duties, while Naruto includes mission reports and village routines and Satisfy includes rankings and class opportunities."},
            {"title": "Messages that answer world events", "example": "Known contacts can send grounded reports or reactions after important developments without requiring another AI request."},
            {"title": "Lower prompt overhead", "example": "A local budget keeps the most relevant abilities, items, people, chats, and campaign facts in each AI request instead of resending unrelated save history."},
            {"title": "Targeted campaign recovery", "example": "Diagnostics can repair only the scene, combat, progression, abilities, NPCs, or world state that became malformed."},
            {"title": "Narrative Satisfy classes", "example": "Overgeared characters normally begin as Beginners and earn a class through story events, with optional Hidden or Legendary class starts still available."},
        ],
    },
    "3.40.0": {
        "title": "A More Consistent Game Master",
        "summary": "This update makes the GM better at remembering the live scene, carrying consequences forward, and keeping narration aligned with the character sheet.",
        "highlights": [
            {"title": "Stronger scene continuity", "example": "People remain where the story placed them, and the GM remembers the immediate danger, question, and objective."},
            {"title": "One-pass response repair", "example": "Incomplete or contradictory GM responses receive one targeted correction only when a local check proves it is needed."},
            {"title": "Narrative and mechanics agree", "example": "A claimed awakening, mastery, or transformation must leave an appropriately durable result."},
            {"title": "Canon changes keep changing canon", "example": "Prevented or altered events now carry their effects into dependent future events instead of snapping back to the original plot."},
            {"title": "Promises and delayed consequences persist", "example": "Debts, deadlines, betrayals, and long-term fallout can become due later instead of being forgotten after one turn."},
            {"title": "More varied pacing", "example": "The GM notices repeated combat, training, social, or travel beats and varies the next development through existing story threads."},
            {"title": "Advisor evidence", "example": "Advisor answers now include an expandable explanation of the campaign facts and current mechanics behind the answer."},
            {"title": "Lower lore overhead", "example": "Lore retrieval is skipped when the live campaign already contains enough evidence, while canon-heavy questions still receive source grounding."},
            {"title": "Learns from liked turns", "example": "Turns marked as good gently teach the GM your preferred detail and kinds of scenes without changing difficulty or outcomes."},
        ],
    },
}


def notes_for(version):
    notes = RELEASE_NOTES.get(str(version), {})
    return {"version": str(version), **notes} if notes else {"version": str(version), "title": "Worldwalker Updated", "summary": "A new version is ready.", "highlights": []}
