'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view=null,mode='move',aim=null,busy=false,pending=null,selected=null,lastSignature='';
const fx=new UnityBattleFX($('fx'),$('ground'));fx.clear=function(){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);this.ground?.clearRect(0,0,$('ground').width,$('ground').height);};
const safeURL=s=>{try{const u=new URL(s,location.href);return u.origin===location.origin?u.href:null;}catch{return null;}};
function portrait(u){
 const base=safeURL(u.basePortrait||u.portrait_url||'');
 const active=u.player?view.portrait_identity?.active_form:u.portrait_identity?.active_form;
 const identity=u.identity||u.canon_identity||({'naruto uzumaki':'naruto','sasuke uchiha':'sasuke','kakashi hatake':'kakashi','monkey d. luffy':'luffy','luffy':'luffy','roronoa zoro':'zoro'}[u.name.toLowerCase()]);
 const exact=identity&&active?.name?(window.APPROVED_ART||[]).find(a=>a.identity===identity&&(a.state===u.form_id||a.name.toLowerCase()===active.name.toLowerCase())):null;
 if(exact){const a=exact.atlas;return `<svg viewBox="${a.column} ${a.row} 1 1"><image href="../assets/approved/${esc(exact.file)}" width="${a.columns}" height="${a.rows}" preserveAspectRatio="none"/></svg>`;}
 if(base&&u.portrait_url)return `<img src="${esc(base)}" alt="${esc(u.name)}">`;
 // Never show a future form, a different named character, or unapproved replacement.
 const world=String(view?.world||'naruto').toLowerCase().replace(/[^a-z0-9]+/g,'_');
 const row=(window.CanonBattleLibrary?.entries||[]).find(r=>r.userApproved&&r.world===world&&r.name.toLowerCase()===u.name.toLowerCase());
 if(row){const r=row.rect;return `<svg viewBox="${r.x} ${r.y} ${r.width} ${r.height}"><image href="../assets/canon-battle-library/${esc(row.file)}" width="${row.imageWidth}" height="${row.imageHeight}"/></svg>`;}
 return `<span aria-label="Portrait unavailable">${esc(u.name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</span>`;
}
function player(){return view?.board.units.find(u=>u.id===(view.viewer_id||'player'));}
function facing(x,y){const p=player(),dx=x-p.x,dy=y-p.y;return Math.abs(dx)>Math.abs(dy)?dx>0?'east':'west':dy>0?'south':'north';}
function area(x,y){const p=player(),raw=view.board.skill_profiles?.[$('skills').value]?.tactical||{shape:'single',range:1};const s={origin:'target',range:1,length:1,width:1,radius:0,...raw};let out=[];if(s.origin==='target'&&Math.abs(x-p.x)+Math.abs(y-p.y)>s.range)return out;const [dx,dy]={north:[0,-1],east:[1,0],south:[0,1],west:[-1,0]}[facing(x,y)];
 if(s.shape==='self')out=[[p.x,p.y]];else if(s.shape==='single')out=[[x,y]];else if(['burst','ring','cross'].includes(s.shape)){const [cx,cy]=s.origin==='self'?[p.x,p.y]:[x,y];for(let a=cx-s.radius;a<=cx+s.radius;a++)for(let b=cy-s.radius;b<=cy+s.radius;b++){const d=Math.abs(a-cx)+Math.abs(b-cy);if(d<=s.radius&&(s.shape!=='ring'||d===s.radius)&&(s.shape!=='cross'||a===cx||b===cy))out.push([a,b]);}}
 else for(let depth=1;depth<=(s.shape==='arc'?1:s.length);depth++){const half=s.shape==='cone'?depth-1:Math.floor(s.width/2);for(let k=-half;k<=half;k++)out.push([p.x+dx*depth-dy*k,p.y+dy*depth+dx*k]);}
 return out.filter(([a,b])=>a>=0&&b>=0&&a<view.board.width&&b<view.board.height&&(!s.exclude_origin||a!==p.x||b!==p.y)&&
  (s.effect!=='summon'||(!view.board.obstacles.some(o=>o.x===a&&o.y===b)&&!view.board.units.some(u=>!u.defeated&&u.hp>0&&u.x===a&&u.y===b))));}
function highlight(x,y){if(!view)return;const keys=new Set((mode==='move'?view.board.reachable||[]:Number.isInteger(x)?area(x,y):[]).map(p=>p.join(',')));for(const t of $('tiles').children)t.className='tile'+(keys.has(t.dataset.key)?mode==='move'?' reachable':' target-area':'');}
function render(){if(!view?.board)return;const b=view.board,p=player();if(!p)return;selected??=p.id;
 document.body.dataset.world=view.world||'Naruto';document.title=`${view.world||'Worldwalker'} tactical battle — local`;$('world-name').textContent=view.world||'Tactical Combat';
 $('heading').textContent=view.combat.active?`${view.world||'Naruto'} encounter`:`Battle ${view.combat.outcome||'finished'}`;$('round').textContent='ROUND '+(view.combat.round||b.activation||1);$('order').textContent=b.units.find(u=>u.id===b.active_id)?.name||'';
 $('turn-state').textContent=view.is_turn===false?'Waiting for the other player':b.bonus_activation?'Your bonus choice':'Your turn';const resource=view.world==='One Piece'?'Stamina':'Chakra';$('resources').textContent=`${p.name} · HP ${p.hp}/${p.hp_max} · ${resource} ${p.resource}/${p.resource_max} · Move ${p.movement_left} · Action ${p.action_used?0:1}`;
 const skill=$('skills').value,form=$('forms').value;const profiles=b.skill_profiles||{};$('skills').innerHTML='<option value="">Plain attack</option>';$('forms').innerHTML='';for(const [name,d]of Object.entries(profiles)){const option=document.createElement('option');option.value=name;option.textContent=name+(d.tactical_disabled?' — unavailable':'');option.disabled=!!d.tactical_disabled;((d.tactical?.effect||d.effect_type)==='transform'?$('forms'):$('skills')).append(option);}
 if([...$('skills').options].some(o=>o.value===skill))$('skills').value=skill;if([...$('forms').options].some(o=>o.value===form))$('forms').value=form;
 $('skill-detail').textContent=profiles[$('skills').value]?.description||'Select a learned technique, then aim at the board.';
 $('unavailable').textContent=Object.entries(profiles).filter(([,d])=>d.tactical_disabled).map(([name,d])=>name+': '+d.tactical_disabled).join('\n');
 $('board').style.setProperty('--size',b.width);for(const id of ['terrain','ground','fx']){const c=$(id);if(c.width!==b.width*100)c.width=c.height=b.width*100;}
 const ctx=$('terrain').getContext('2d'),onePiece=view.world==='One Piece';ctx.fillStyle=onePiece?'#8b633e':'#526a50';ctx.fillRect(0,0,b.width*100,b.height*100);if(onePiece){ctx.strokeStyle='#5d3c27';ctx.lineWidth=4;for(let y=0;y<=b.height;y++){ctx.beginPath();ctx.moveTo(0,y*100);ctx.lineTo(b.width*100,y*100);ctx.stroke();}}for(const o of b.obstacles){ctx.fillStyle=o.kind==='tree'?'#294734':onePiece?'#58412f':'#929a83';if(onePiece&&o.kind!=='tree'){ctx.fillRect(o.x*100+20,o.y*100+22,60,56);ctx.strokeStyle='#c39a5d';ctx.strokeRect(o.x*100+20,o.y*100+22,60,56);}else{ctx.beginPath();ctx.arc(o.x*100+50,o.y*100+50,30,0,7);ctx.fill();}}
 if($('tiles').children.length!==b.width*b.height){$('tiles').replaceChildren();for(let y=0;y<b.height;y++)for(let x=0;x<b.width;x++){const t=document.createElement('button');t.dataset.key=`${x},${y}`;t.setAttribute('aria-label',`Tile ${String.fromCharCode(65+x)}${y+1}`);t.onclick=()=>choose(x,y);t.onpointerenter=t.onfocus=()=>highlight(x,y);$('tiles').append(t);}}
 $('roster').innerHTML=b.units.map(u=>`<button class="roster-unit" data-id="${esc(u.id)}">${esc(u.name)}<small>${u.hp}/${u.hp_max} HP</small></button>`).join('');$('roster').querySelectorAll('button').forEach(el=>el.onclick=()=>{selected=el.dataset.id;inspect();});
 const live=new Set();for(const u of b.units){live.add('piece-'+u.id);let el=$('piece-'+u.id);if(!el){el=document.createElement('button');el.id='piece-'+u.id;$('pieces').append(el);}el.hidden=!!u.defeated;el.className='piece '+u.side;el.style.setProperty('--x',u.x);el.style.setProperty('--y',u.y);el.innerHTML=`<span class="avatar">${portrait(u)}</span><span class="piece-label">${esc(u.name)}</span>`;el.setAttribute('aria-label',`${u.name}, ${u.hp} HP`);el.onclick=()=>{selected=u.id;inspect();if(mode==='attack')choose(u.x,u.y);};}for(const el of [...$('pieces').children])if(!live.has(el.id))el.remove();
 $('log').innerHTML=(view.combat.log||[]).slice(-12).map(r=>`<li>${esc(r.name||r.actor)} · ${esc(r.ability||r.action)}${r.damage!==undefined?' · '+r.damage+' damage':''}</li>`).join('');$('story').disabled=!!view.combat.active;
 for(const id of ['move','attack','defend','end','transform','revert','flee'])$(id).disabled=busy||view.is_turn===false||!view.combat.active;
 $('flee').disabled||=!!b.owners&&!p.player;$('flee').title=b.owners?'The host controls party retreat.':'';
 $('transform').disabled||=!$('forms').options.length;$('confirm').disabled=busy||!aim||view.is_turn===false||!view.combat.active;inspect();highlight(aim?.x,aim?.y);
}
function inspect(){const u=view.board.units.find(u=>u.id===selected)||player();$('identity').innerHTML=portrait(u)+`<h3>${esc(u.name)}</h3>`;$('inspected-stats').textContent=`Power ${u.power} · Defense ${u.defense} · Speed ${u.speed}`;$('condition').textContent=(u.statuses||[]).map(s=>s.name).join(', ')||'No disabling conditions';}
function choose(x,y){if(busy||!view.combat.active||view.is_turn===false)return;if(mode==='attack'&&!area(x,y).length){aim=null;$('hint').textContent='That tile is outside this ability’s valid range or shape.';highlight();$('confirm').disabled=true;return;}if(mode==='move'&&!(view.board.reachable||[]).some(p=>p[0]===x&&p[1]===y)){aim=null;$('hint').textContent='That tile is not reachable with the movement remaining.';highlight();$('confirm').disabled=true;return;}aim={x,y};$('hint').textContent=mode==='move'?'Confirm movement to the highlighted tile.':'Orange tiles show the exact affected area. Confirm to cast.';highlight(x,y);$('confirm').disabled=false;}
async function fetchJSON(url,options){const r=await fetch(url,{signal:AbortSignal.timeout(15000),...options});const data=await r.json();if(!r.ok){const error=Error(data.error||'Request failed');error.status=r.status;throw error;}return data;}
async function refresh(){if(busy)return;try{const data=await fetchJSON('/api/combat/tactical');if(data.enabled===false){$('hint').textContent='Load a supported tactical save with active combat, then connect.';return;}view=data;render();}catch(e){$('hint').textContent=e.message;}}
async function send(action,extra={}){if(busy)return;busy=true;render();try{if(!pending){let csrf='';try{const a=await fetchJSON('/api/auth/status');csrf=a.csrf_token||'';}catch{}pending={body:{action,revision:view?.board.revision,request_id:crypto.randomUUID(),...extra},csrf};}const before=player()?{x:player().x,y:player().y}:null;const data=await fetchJSON('/api/combat/tactical',{method:'POST',headers:{'Content-Type':'application/json','X-Worldwalker-CSRF':pending.csrf},body:JSON.stringify(pending.body)});pending=null;$('retry').hidden=true;aim=null;busy=false;await refresh();busy=true;
 const log=data.combat?.log||[],event=log.at(-1);if(event?.cutin){$('form-title').textContent=event.form;$('form-art').innerHTML=portrait(player());$('form-boosts').textContent=Object.entries(event.boosts||{}).filter(([k])=>k.endsWith('_pct')).map(([k,v])=>`${k.replace('_pct','')}: ${Math.round(v*100)}%`).join(' · ');$('cutin').showModal();setTimeout(()=>$('cutin').close(),$('reduced').checked?500:2200);}
 else if(event?.affected_tiles?.length&&event.origin){fx.forcedReduced=$('reduced').checked;const destination=event.destination?{x:event.destination[0],y:event.destination[1]}:{x:event.affected_tiles[0][0],y:event.affected_tiles[0][1]};await fx.play({id:String(view.board.revision),name:event.ability,origin:event.origin,aim:destination,shape:event.shape||'single',facing:{north:'n',south:'s',east:'e',west:'w'}[extra.facing]||'e',cells:event.affected_tiles.map(p=>p.join(',')),element:'energy',effect:event.visual?.asset?event.visual:null,hits:[]});}
 $('hint').textContent='Command resolved.';
 }catch(e){$('hint').textContent=e.message;if(e.status>=400&&e.status<500)pending=null;$('retry').hidden=!pending;}finally{busy=false;render();}}
 $('enable').onclick=()=>send('enable');$('refresh').onclick=refresh;$('phone').onclick=()=>$('frame').classList.toggle('phone');$('enlarge').onclick=()=>$('board-scroll').classList.toggle('enlarged');$('skills').onchange=()=>{mode='attack';aim=null;render();};$('move').onclick=()=>{mode='move';aim=null;render();};$('attack').onclick=()=>{mode='attack';aim=null;render();};$('confirm').onclick=()=>aim&&send(mode==='move'?'move':'attack',{...aim,facing:facing(aim.x,aim.y),ability:$('skills').value});$('defend').onclick=()=>send('defend');$('end').onclick=()=>send('end');$('flee').onclick=()=>send('flee');$('revert').onclick=()=>send('revert');$('transform').onclick=()=>send('transform',{ability:$('forms').value});$('retry').onclick=()=>send(pending?.body.action);$('story').onclick=()=>location.href='/';$('skip').onclick=()=>$('cutin').close();document.addEventListener('visibilitychange',()=>{if(document.hidden)$('cutin').close();else refresh();});setInterval(refresh,3000);refresh();
